#!/usr/bin/env Rscript

# Exploratory Data Analysis for Club World Cup data
# This script loads the most recent data set generated by cwc_pull.R,
# expands the nested tables and produces a few basic summaries and charts.

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(readr)
})

out_dir <- "data/out"
files <- list.files(out_dir, pattern = "\.rds$", full.names = TRUE)
if (length(files) == 0) {
  stop("No RDS files found in data/out/")
}
latest_file <- files[which.max(file.mtime(files))]
message("Loading ", latest_file)
big_df <- readRDS(latest_file)

# Unnest tables -----------------------------------------------------------

matches <- big_df %>% select(team, matches) %>% tidyr::unnest(matches)
team_stats <- big_df %>% select(team, team_stats) %>% tidyr::unnest(team_stats)
player_stats <- big_df %>% select(team, player_stats) %>% tidyr::unnest(player_stats)

analysis_dir <- "analysis"
dir.create(analysis_dir, showWarnings = FALSE, recursive = TRUE)

# Goals scored ------------------------------------------------------------

goal_col <- names(team_stats)[grepl("^goals?$|gls", names(team_stats), ignore.case = TRUE)][1]
if (!is.na(goal_col)) {
  goals_by_team <- team_stats %>%
    group_by(team) %>%
    summarise(goals = sum(.data[[goal_col]], na.rm = TRUE)) %>%
    arrange(desc(goals))

  g <- ggplot(goals_by_team, aes(x = reorder(team, goals), y = goals)) +
    geom_col(fill = "steelblue") +
    coord_flip() +
    labs(x = "Team", y = "Goals", title = "Goals scored by team")

  ggsave(file.path(analysis_dir, "goals_by_team.png"), g, width = 8, height = 6)
  write_csv(goals_by_team, file.path(analysis_dir, "goals_by_team.csv"))
}

# Possession --------------------------------------------------------------

poss_col <- names(team_stats)[grepl("poss", names(team_stats), ignore.case = TRUE)][1]
if (!is.na(poss_col)) {
  poss_by_team <- team_stats %>%
    group_by(team) %>%
    summarise(possession = mean(.data[[poss_col]], na.rm = TRUE))

  g <- ggplot(poss_by_team, aes(x = reorder(team, possession), y = possession)) +
    geom_col(fill = "darkgreen") +
    coord_flip() +
    labs(x = "Team", y = "Possession", title = "Average possession (%)")

  ggsave(file.path(analysis_dir, "possession_by_team.png"), g, width = 8, height = 6)
  write_csv(poss_by_team, file.path(analysis_dir, "possession_by_team.csv"))
}

# Disciplinary stats ------------------------------------------------------

card_cols <- names(team_stats)[grepl("crd|card", names(team_stats), ignore.case = TRUE)]
if (length(card_cols) > 0) {
  disc <- team_stats %>%
    group_by(team) %>%
    summarise(across(all_of(card_cols), ~ sum(.x, na.rm = TRUE)))

  disc_long <- disc %>%
    pivot_longer(-team, names_to = "type", values_to = "value")

  g <- ggplot(disc_long, aes(x = reorder(team, value), y = value, fill = type)) +
    geom_col(position = "dodge") +
    coord_flip() +
    labs(x = "Team", y = "Cards", title = "Disciplinary stats by team")

  ggsave(file.path(analysis_dir, "disciplinary_by_team.png"), g, width = 8, height = 6)
  write_csv(disc, file.path(analysis_dir, "disciplinary_stats.csv"))
}

message("Outputs written to ", analysis_dir)

